version: 2
updates:
  - package-ecossystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    groups:
      development-dependencies:
        patterns:
          - "*"
