# test on cpython and pypy
name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "pypy3.10"
          - "3.11"
          - "pypy3.11"
          - "3.12"
          - "pypy3.12"
          - "3.13"
          - "pypy3.13"
          - "3.14"
          - "pypy3.14"
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13' 
          cache: 'poetry'

      - name: Run tests with coverage
        run: coverage run --source=src -m pytest

      - name: Publish coverage on workflow summary
        run: coverage report --format=markdown >> ${GITHUB_STEP_SUMMARY}
